---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: archlinux:latest
    commands:
      - pacman -Syu --noconfirm bash coreutils findutils git imagemagick inkscape make pandoc python python-beautifulsoup4 python-django python-feedparser python-yaml sed
      - make build
