#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace
import csv
import datetime
import json
import os
import sys

def getopts() -> Namespace:
    ap = ArgumentParser()
    ap.add_argument("donations_csv")
    return ap.parse_args()

def mtime(path: str) -> str:
    return (datetime.datetime.fromtimestamp(os.stat(path).st_mtime)
                .strftime('%Y-%m-%d'))

def main():
    opts = getopts()
    records = {}
    headermap = {}

    with open(opts.donations_csv, "r", encoding='utf-8-sig') as FILE:
        tid = -1
        data = csv.reader(FILE)
        header = True
        for row in data:
            if header:
                header = not header
                coli = 0
                for c in row:
                    headermap[coli] = c
                    if c == "Transaction ID":
                        tid = coli
                    coli += 1
            else:
                rowdata = {}
                for i in range(0, len(row)):
                    rowdata[headermap[i]] = row[i]
                records[row[tid]] = rowdata

    fee       = 0.0
    gross     = 0.0
    net       = 0.0
    net_ex    = 0.0
    net_in    = 0.0

    shortfall = 0
    yearly    = 500
    reserve   = yearly * 1.5
    yearzero  = 2016
    year = yearzero

    for tid in records:
        r = records[tid]
        if r["Currency"] == "USD":
            gross += float(r["Gross"])
            fee += float(r["Fee"])

            n = float(r["Net"])
            net += n
            if n < 0.0:
                net_ex += n
            elif n > 0.0:
                net_in += n

    shortfall = net_in
    while shortfall >= 0:
        want = 0
        if year == yearzero:
            want += reserve
        want += yearly
        shortfall -= want
        year += 1

    print(json.dumps({
        "short_year": year,
        "short_pct": round(abs(shortfall)/yearly, 2),
        "want_pa": yearly,
        "reserve": reserve,
        "last_update": mtime(opts.donations_csv),
        }, indent=2))

    return 0

if __name__ == "__main__":
    sys.exit(main())
