#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace
from csv import DictReader
import datetime
import json
import os
import sys

def getopts() -> Namespace:
    ap = ArgumentParser()
    ap.add_argument("donations_csv", help="PayPal activity report (CSV)")
    return ap.parse_args()

def mtime(path: str) -> str:
    return (datetime.datetime.fromtimestamp(os.stat(path).st_mtime)
                .strftime('%Y-%m-%d'))

def main():
    opts = getopts()

    fee       = 0.0
    gross     = 0.0
    net       = 0.0
    net_ex    = 0.0
    net_in    = 0.0
    shortfall = 0
    yearly    = 500
    reserve   = yearly * 1.5
    yearzero  = 2016
    year      = yearzero

    FILE = open(opts.donations_csv, "r", encoding='utf-8-sig')
    reader = DictReader(FILE)

    for r in reader:
        if r["Currency"] == "USD":
            gross += float(r["Gross"])
            fee += float(r["Fee"])

            n = float(r["Net"])
            net += n
            if n < 0.0:
                net_ex += n
            elif n > 0.0:
                net_in += n

    FILE.close()

    shortfall = net_in
    while shortfall >= 0:
        want = 0
        if year == yearzero:
            want += reserve
        want += yearly
        shortfall -= want
        year += 1

    print(json.dumps({
        "short_year": year,
        "short_pct": round(abs(shortfall)/yearly, 2),
        "want_pa": yearly,
        "reserve": reserve,
        "last_update": mtime(opts.donations_csv),
        }, indent=2))

    return 0

if __name__ == "__main__":
    sys.exit(main())
