#!/usr/bin/env python3

import sys
import yaml

def entry(stem, alt):
    return """<a href="/img/frontpage-gallery/{}.jpg" title="Screenshot by {}" target="_blank">\
<img alt="[ Screenshot by {} ]" src="/img/frontpage-gallery/thumbs/{}.thumb.jpg"></a>""".format(stem, alt, alt, stem)

if __name__ == "__main__":
    print("""<div class="gallery">""")
    print("""<h2>Screenshots</h2>""")
    with open(sys.argv[1], "r") as FILE:
        for img in yaml.load(FILE, Loader=yaml.SafeLoader)['gallery']:
            print(entry(img['base'] if 'base' in img else img['author'], img['author']))
    print("""</div>""")
