#!/bin/bash

set -e

readonly INFILE=$1
readonly OUTDIR=$(dirname -- "$1");
readonly GENFILE=$2

shift 2

{ 
  for size in "$@"; do

    printf "\t%03dpx favicon ... " "$size" >&2
    inkscape -h "$size" -w "$size" -C -o "$OUTDIR/favicon${size}.png" -- "$INFILE"
    echo "done." >&2

    if [[ $size = 180 ]]; then
      echo "<link rel='apple-touch-icon' href='/img/favicon${size}.png'>"
    else
      echo "<link rel='icon' href='/img/favicon${size}.png' sizes='${size}x${size}'>"
    fi

  done
} > "$GENFILE"
